### PR TITLE
Added more symbols

### PR DESCRIPTION
**Pull request by Gabriel0402**

### CODE REVIEW

**Comment by tshoang** [comment]
@Gabriel0402 Thank you very much. Can you please run "make" and commits the generated files as well?

**Review by tshoang — CHANGES_REQUESTED** [review]
The generated files should be produced (using Make) and submitted as well.

**Comment by Gabriel0402** [comment]
Produce files with make command

**Comment by tshoang** [comment]
@Gabriel0402 Why did you close the pull request? 😆 Just push to your fork and the new files will be included in the pull request.

**Review by tshoang — APPROVED** [review]

**Comment by Gabriel0402** [comment]
Sorry for the confusion, I've tried to push my commits but I didn't see the changes in this PR. And I accidentally closed the PR and cannot reopen the PR. Thanks for approving the PR.

**Pull request merged**
